### ISSUE TITLE
Content misplacement?

### ISSUE THREAD

**Issue by yacoubod** [MLH/mlh-hackathon-rules#1]
"But make sure to check how many prizes are available per team. If a large team wins a challenge, there might not be enough prizes for everyone."
- This seems like it belongs in "Advice to Organizers" doc, not in the rules.
- Also the word "your" is misspelled in the "demos" section.
- Otherwise looks good and is super useful!

**Comment by tfogo** [comment]
Thanks @yacoubod!

The advice to check how many prizes are available per team is advice to the participants. The point is that people can form teams of any size but they should keep in mind that there is a limited number of prizes. I'll edit it to make it a bit clearer.
